"""The run client: a generated run id, and the four calls that carry it.

PRD 5.4: "**the run id is generated by the client library when it is
initialised**, before the first call, and is passed on every ``fetch_step`` and
``record_step`` for the whole end-to-end execution." That is what
:class:`RunClient` and :class:`AsyncRunClient` are - a run id plus an agent id,
and every request shaped around them.

Ground rule 9 permits exactly one ``uuid4()`` in this system and it is here.
"Run ids are generated by the *client*, not the service, so ``uuid4()`` is
correct there. It is generation and expansion inside the service that must be
seeded." `tests/unit/test_layering.py` forbids the *import* of a random source
in every layer of `src/`, which is what makes that division mechanical rather
than remembered.

Four properties follow from the id being generated up front, and they are the
reason this class exists rather than a bag of functions:

1. **Retries are safe.** ``(run_id, step_key, iteration)`` is an idempotency
   key. Re-``fetch_step`` returns the identical fixture and advances nothing;
   re-``record_step`` with the same actual is a no-op; re-``run_finish`` with
   the same outcome is a no-op. A network retry cannot corrupt a run.
2. **The path is reconstructed, not declared.** The ordered sequence of calls
   carrying the id *is* the traversal, so there is no ``path_hint`` to send and
   no way for an agent to lie about where it went.
3. **Concurrency is free.** N executions are N clients with N ids and no
   coordination.
4. **Idempotency never expires**, because the id is the primary key of a
   permanently stored record.

Sync and async, from one set of pure functions
----------------------------------------------

The milestone asks for both APIs. They are two thin facades over the *same*
request-shaping and response-reading functions - :func:`_step_arguments`,
:func:`_step_of`, :func:`_record_of` and friends - so the two APIs cannot
disagree about what a request looks like or what a response means. Each method
is one line of transport plus a shared call: ``await self._call(...)`` or
``self._call(...)``.

Two alternatives were weighed and both were worse. Generating the sync client
from the async one (an ``unasync``-style build step) makes the code you read
different from the code that runs. Wrapping every async method in
``asyncio.run`` per call makes the sync client re-open a session per request,
which for a stdio server means spawning the process again per step - and it
buries the lifecycle in a place a caller cannot see. Instead the *transport*
owns the bridge, once, in `session.py`, and both facades take a plain callable.

Which is also why this module imports **no transport at all**. It takes a
callable that turns ``(tool, arguments)`` into an envelope, so it can be driven
by an in-memory MCP session, a subprocess, an HTTP server or a test double
without knowing the difference - and so `compare.py` and this module are both
usable by someone with no server and no network.
"""

from __future__ import annotations

import re
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass
from typing import Any, Final
from uuid import uuid4

from agentprops_client.envelope import Envelope, ToolError, Warning, read_envelope

__all__ = [
    "RUN_ID_MAX_LENGTH",
    "RUN_ID_MIN_LENGTH",
    "RUN_ID_PATTERN",
    "STATUS_ABANDONED",
    "STATUS_FINISHED",
    "AsyncRunClient",
    "Recorded",
    "RunClient",
    "RunStart",
    "Step",
    "new_run_id",
]

#: contracts 2.3: "The run id is a client-supplied opaque string, 8 to 128
#: characters, ``^[A-Za-z0-9_.:-]+$``. The service does not generate it and does
#: not parse meaning from it."
RUN_ID_PATTERN: Final = re.compile(r"^[A-Za-z0-9_.:-]+$")
RUN_ID_MIN_LENGTH: Final = 8
RUN_ID_MAX_LENGTH: Final = 128

#: The two statuses ``run_finish`` accepts. ``running`` is not one: the tool
#: closes a run.
STATUS_FINISHED: Final = "finished"
STATUS_ABANDONED: Final = "abandoned"

#: A synchronous transport: one tool call, one raw payload.
type SyncCall = Callable[[str, dict[str, Any]], Mapping[str, Any] | None]

#: The same, awaited.
type AsyncCall = Callable[[str, dict[str, Any]], Awaitable[Mapping[str, Any] | None]]


def new_run_id() -> str:
    """A fresh run id. Ground rule 9's one sanctioned ``uuid4()``.

    A bare UUID rather than a prefixed string: it is 36 characters, matches
    ``^[A-Za-z0-9_.:-]+$``, and the service "does not parse meaning from it", so
    a prefix would be decoration that some caller eventually tried to read.
    A caller who wants a meaningful id passes their own.
    """
    return str(uuid4())


def check_run_id(run_id: str) -> str:
    """``run_id`` if the service will accept it, else ``ValueError``.

    A convenience, not the authority: `service/runs.py` checks the same three
    things and answers ``AP-001``, and that is what a caller sending a bad id
    over any other client will see. Raising here is right for a *library*
    argument, and it is the one place this client raises for something other
    than a tool failure - it fails at construction, before the run exists,
    rather than one call later.
    """
    if not RUN_ID_MIN_LENGTH <= len(run_id) <= RUN_ID_MAX_LENGTH:
        raise ValueError(
            f"a run id is {RUN_ID_MIN_LENGTH} to {RUN_ID_MAX_LENGTH} characters; got {len(run_id)}"
        )
    if not RUN_ID_PATTERN.fullmatch(run_id):
        raise ValueError(f"a run id must match {RUN_ID_PATTERN.pattern}; got {run_id!r}")
    return run_id


@dataclass(frozen=True, slots=True)
class RunStart:
    """What ``run_start`` pinned, and anything it warned about."""

    run: Mapping[str, Any]
    pin: Mapping[str, Any]
    warnings: tuple[Warning, ...]

    @property
    def dataset_id(self) -> str:
        return str(self.pin["dataset_id"])

    @property
    def dataset_version(self) -> int:
        return int(self.pin["dataset_version"])

    @property
    def blueprint_version(self) -> str:
        return str(self.pin["blueprint_version"])


@dataclass(frozen=True, slots=True)
class Step:
    """One served step: the authored fixture, and which node it came from.

    ``resolved_node_id`` is the field a ``tool_name`` caller cannot compute for
    itself, and the whole reason tool-name addressing is usable: the same tool
    name resolves to different nodes depending on where the run is.
    """

    fixture: Mapping[str, Any]
    resolved_node_id: str
    warnings: tuple[Warning, ...]

    @property
    def output(self) -> Mapping[str, Any]:
        """``fixture["output"]`` - what the world returns to the agent.

        The one field an agent actually consumes. ``input`` is what the author
        expects the agent to have sent, and ``expected.final`` is what the agent
        should produce; PRD 5.2 calls mixing those "the single easiest way to
        build a confusing product", so this property names the one that is the
        tool's answer.
        """
        return dict(self.fixture.get("output") or {})


@dataclass(frozen=True, slots=True)
class Recorded:
    """The stored step after ``record_step``, and which node it landed on.

    ``step["actual"]`` is the **stored** actual, which on a conflict is the one
    recorded first rather than the one just sent - see
    ``step_actual_conflict`` in contracts 3.4.
    """

    step: Mapping[str, Any]
    resolved_node_id: str
    warnings: tuple[Warning, ...]

    @property
    def actual(self) -> Mapping[str, Any]:
        return dict(self.step.get("actual") or {})


class _Requests:
    """Every request this client sends, as pure argument dicts.

    A class of static methods purely to keep them together and named: nothing
    here touches a transport, so the two facades below can share them and the
    sync and async APIs cannot drift into sending different requests.

    ``None`` values are dropped rather than sent, because an omitted optional
    argument and an explicit ``null`` are different things to the tool surface:
    ``fetch_step(node_id=None, tool_name=None)`` is "no address at all" and
    answers RT-E02, which is the correct answer to a caller who addressed
    nothing - but a client that sent ``iteration: null`` for every non-pool step
    would be relying on the surface treating null as absent.
    """

    @staticmethod
    def start(
        run_id: str,
        agent_id: str,
        selector: Mapping[str, Any],
        declared_blueprint_version: str | None,
        model: Mapping[str, Any] | None,
        run_class: str | None,
    ) -> dict[str, Any]:
        return _present(
            run_id=run_id,
            agent_id=agent_id,
            selector=dict(selector),
            declared_blueprint_version=declared_blueprint_version,
            model=None if model is None else dict(model),
            run_class=run_class,
        )

    @staticmethod
    def step(
        run_id: str, node_id: str | None, tool_name: str | None, iteration: int | None
    ) -> dict[str, Any]:
        return _present(run_id=run_id, node_id=node_id, tool_name=tool_name, iteration=iteration)

    @staticmethod
    def record(
        run_id: str,
        actual: Mapping[str, Any],
        node_id: str | None,
        tool_name: str | None,
        iteration: int | None,
    ) -> dict[str, Any]:
        return _present(
            run_id=run_id,
            actual=dict(actual),
            node_id=node_id,
            tool_name=tool_name,
            iteration=iteration,
        )

    @staticmethod
    def finish(run_id: str, outcome: Mapping[str, Any], status: str) -> dict[str, Any]:
        return {"run_id": run_id, "outcome": dict(outcome), "status": status}


class _Responses:
    """Every response this client reads, as pure functions of an envelope.

    The failure decision is here and **only** here: a typed result cannot
    represent a failure, so an ``{ok: false}`` envelope becomes a
    :class:`ToolError` carrying every finding. ``call()`` on either facade
    bypasses this and hands back the envelope, which is how a caller inspects a
    rule id as data.
    """

    @staticmethod
    def start(envelope: Envelope) -> RunStart:
        payload = _checked(envelope, "run_start").payload("start")
        return RunStart(
            run=dict(payload["run"]), pin=dict(payload["pin"]), warnings=envelope.warnings
        )

    @staticmethod
    def step(envelope: Envelope) -> Step:
        payload = _checked(envelope, "fetch_step").payload("step")
        return Step(
            fixture=dict(payload["fixture"]),
            resolved_node_id=str(payload["resolved_node_id"]),
            warnings=envelope.warnings,
        )

    @staticmethod
    def record(envelope: Envelope) -> Recorded:
        payload = _checked(envelope, "record_step").payload("record")
        return Recorded(
            step=dict(payload["step"]),
            resolved_node_id=str(payload["resolved_node_id"]),
            warnings=envelope.warnings,
        )

    @staticmethod
    def finish(envelope: Envelope) -> Mapping[str, Any]:
        return _checked(envelope, "run_finish").payload("run")


class RunClient:
    """The synchronous client. One run, one id, generated at construction.

    ``call`` is a callable taking ``(tool_name, arguments)`` and returning the
    raw payload - `session.py` builds one over an MCP session, and a test can
    pass a function. Nothing about the transport is visible here, which is what
    keeps this module free of a network import.
    """

    def __init__(self, call: SyncCall, *, agent_id: str, run_id: str | None = None) -> None:
        self._call_tool = call
        self.agent_id = agent_id
        self.run_id = check_run_id(run_id) if run_id is not None else new_run_id()

    def call(self, tool: str, **arguments: Any) -> Envelope:
        """Any tool, raw. Returns the envelope and **raises nothing** for ``ok: false``.

        The escape hatch, and it is not an afterthought: the authoring tools
        (``blueprint_upsert``, ``dataset_skeleton``, ``dataset_fill_part``,
        ``dataset_submit``) have no typed wrapper here because they are not part
        of a run, and a caller inspecting ``SK-002`` or ``DS-017`` as data needs
        the envelope rather than an exception.
        """
        return read_envelope(self._call_tool(tool, dict(arguments)))

    def run_start(
        self,
        selector: Mapping[str, Any],
        *,
        declared_blueprint_version: str | None = None,
        model: Mapping[str, Any] | None = None,
        run_class: str | None = None,
    ) -> RunStart:
        """Pin a dataset to this run. ``selector`` is ``{dataset_id}`` or ``{labels}``."""
        return _Responses.start(
            self.call(
                "run_start",
                **_Requests.start(
                    self.run_id,
                    self.agent_id,
                    selector,
                    declared_blueprint_version,
                    model,
                    run_class,
                ),
            )
        )

    def fetch_step(
        self,
        *,
        node_id: str | None = None,
        tool_name: str | None = None,
        iteration: int | None = None,
    ) -> Step:
        """The fixture for one step. Idempotent on the resolved key."""
        return _Responses.step(
            self.call("fetch_step", **_Requests.step(self.run_id, node_id, tool_name, iteration))
        )

    def record_step(
        self,
        actual: Mapping[str, Any],
        *,
        node_id: str | None = None,
        tool_name: str | None = None,
        iteration: int | None = None,
    ) -> Recorded:
        """What the agent produced at one step. Write-once per resolved key."""
        return _Responses.record(
            self.call(
                "record_step",
                **_Requests.record(self.run_id, actual, node_id, tool_name, iteration),
            )
        )

    def run_finish(
        self, outcome: Mapping[str, Any], *, status: str = STATUS_FINISHED
    ) -> Mapping[str, Any]:
        """Close the run with the outcome the agent produced. The first close wins."""
        return _Responses.finish(
            self.call("run_finish", **_Requests.finish(self.run_id, outcome, status))
        )


class AsyncRunClient:
    """The asynchronous client. Identical surface, awaited.

    Every method is the sync one with ``await`` in front of the transport call
    and the *same* request builder and response reader underneath - see the
    module docstring for why that is the whole of the split.
    """

    def __init__(self, call: AsyncCall, *, agent_id: str, run_id: str | None = None) -> None:
        self._call_tool = call
        self.agent_id = agent_id
        self.run_id = check_run_id(run_id) if run_id is not None else new_run_id()

    async def call(self, tool: str, **arguments: Any) -> Envelope:
        """Any tool, raw. Returns the envelope and raises nothing for ``ok: false``."""
        return read_envelope(await self._call_tool(tool, dict(arguments)))

    async def run_start(
        self,
        selector: Mapping[str, Any],
        *,
        declared_blueprint_version: str | None = None,
        model: Mapping[str, Any] | None = None,
        run_class: str | None = None,
    ) -> RunStart:
        """Pin a dataset to this run. ``selector`` is ``{dataset_id}`` or ``{labels}``."""
        return _Responses.start(
            await self.call(
                "run_start",
                **_Requests.start(
                    self.run_id,
                    self.agent_id,
                    selector,
                    declared_blueprint_version,
                    model,
                    run_class,
                ),
            )
        )

    async def fetch_step(
        self,
        *,
        node_id: str | None = None,
        tool_name: str | None = None,
        iteration: int | None = None,
    ) -> Step:
        """The fixture for one step. Idempotent on the resolved key."""
        return _Responses.step(
            await self.call(
                "fetch_step", **_Requests.step(self.run_id, node_id, tool_name, iteration)
            )
        )

    async def record_step(
        self,
        actual: Mapping[str, Any],
        *,
        node_id: str | None = None,
        tool_name: str | None = None,
        iteration: int | None = None,
    ) -> Recorded:
        """What the agent produced at one step. Write-once per resolved key."""
        return _Responses.record(
            await self.call(
                "record_step",
                **_Requests.record(self.run_id, actual, node_id, tool_name, iteration),
            )
        )

    async def run_finish(
        self, outcome: Mapping[str, Any], *, status: str = STATUS_FINISHED
    ) -> Mapping[str, Any]:
        """Close the run with the outcome the agent produced. The first close wins."""
        return _Responses.finish(
            await self.call("run_finish", **_Requests.finish(self.run_id, outcome, status))
        )


def _present(**arguments: Any) -> dict[str, Any]:
    """The arguments that were actually given. See :class:`_Requests`."""
    return {name: value for name, value in arguments.items() if value is not None}


def _checked(envelope: Envelope, request: str) -> Envelope:
    """``envelope`` if it succeeded, else :class:`ToolError` naming the tool."""
    if not envelope.ok:
        raise ToolError(envelope, request)
    return envelope
