"""initial schema: blueprints, datasets, skeletons, runs, run_steps

`docs/contracts.md` section 7's DDL, all five tables, for both SQL dialects.

Autogenerated from :data:`agentprops.storage.sql.METADATA` and then edited in
five places, each of which is a place autogenerate cannot know the intent:

1. **Column types are imported from `storage/sql.py`** rather than re-spelled.
   ``JsonDocument`` and ``UtcDateTime`` carry the two dialect differences
   contracts section 7 names - ``JSONB`` on Postgres, ``TIMESTAMPTZ`` on
   Postgres - so importing them is what keeps this migration and the adapter
   from disagreeing about a column's shape.
2. **``server_default`` uses ``sa.func.now()`` and ``sa.false()``**, not the
   SQLite literals autogenerate rendered (``(CURRENT_TIMESTAMP)`` and ``0``).
   ``DEFAULT 0`` on a boolean is an error on Postgres; these two render
   correctly on both.
3. **``runs_lookup`` is created outside batch mode** with a ``DESC`` third
   column. Batch mode exists to rebuild a table SQLite cannot ``ALTER``; on a
   table created three statements earlier it buys nothing and obscures the
   ``started_at DESC`` the index is for.
4. **The two Postgres-only indexes are created in a dialect branch.**
   ``datasets_labels_gin`` and ``datasets_search`` have no SQLite equivalent -
   contracts section 7 says so, and says SQLite falls back to a scan with
   ``LIKE`` for ``q`` and JSON extraction for labels, which is what
   ``find_datasets`` does. They are absent from ``METADATA`` (``create_all``
   would try to build a GIN index on SQLite) and filtered out of autogenerate
   comparison by env.py, so neither dialect reports drift over them.
5. **``UNIQUE (run_id, seq)`` on ``run_steps``** - an addition to contracts
   section 7 authorised by ruling R-37, and the constraint that makes
   ``upsert_step``'s ``seq`` allocation sound. See the note at the column.

Amended in M3's first fix round rather than superseded by a second revision.
This is the *initial* schema of an unreleased milestone on an unmerged branch:
no database outside a temporary test file has ever been migrated by it, so
there is nothing for an additive revision to migrate *from*. A follow-up
revision would instead make every future deployment replay a SQLite table
rebuild (batch mode) to add a constraint that this statement can simply
declare. Recorded in `DECISIONS.md`; the rule it does not break is the real
one - never edit a revision that has been applied somewhere.

Revision ID: 0001
Revises:
Create Date: 2026-09-09

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from agentprops.storage.sql import JsonDocument, UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "blueprints",
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("document", JsonDocument, nullable=False),
        sa.Column("created_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("status IN ('draft', 'published')", name="blueprints_status_check"),
        sa.PrimaryKeyConstraint("agent_id", "version", name="blueprints_pkey"),
    )

    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("bp_version", sa.Text(), nullable=False),
        sa.Column("archived", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("labels", JsonDocument, nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=False),
        sa.Column("author_handle", sa.Text(), nullable=False),
        sa.Column("author_agent", sa.Text(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column("document", JsonDocument, nullable=False),
        # No DEFAULT now(): ruling R-09 populates this from
        # provenance.created_at so dataset_find's ordering survives an
        # export/import cycle.
        sa.Column("created_at", UtcDateTime, nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id", "bp_version"],
            ["blueprints.agent_id", "blueprints.version"],
            name="datasets_blueprint_fkey",
        ),
        sa.PrimaryKeyConstraint("id", "version", name="datasets_pkey"),
    )
    op.create_index("datasets_lookup", "datasets", ["agent_id", "bp_version", "archived"])
    op.create_index("datasets_author", "datasets", ["author_handle"])

    op.create_table(
        "skeletons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("bp_version", sa.Text(), nullable=False),
        sa.Column("manifest", JsonDocument, nullable=False),
        sa.Column("parts", JsonDocument, server_default=sa.text("'{}'"), nullable=False),
        sa.Column("submitted_as", sa.Uuid(), nullable=True),
        sa.Column("created_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "runs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_ver", sa.Integer(), nullable=False),
        sa.Column("bp_version", sa.Text(), nullable=False),
        # Not in contracts section 7. Contracts section 2.3 gives Run a
        # `declared_blueprint_version` and the DDL has no column for it; see
        # storage/sql.py's note on the `runs` table and the M3 report.
        sa.Column("declared_bp_version", sa.Text(), nullable=True),
        sa.Column("run_class", sa.Text(), server_default=sa.text("'dev'"), nullable=False),
        sa.Column("model", JsonDocument, nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("outcome", JsonDocument, nullable=True),
        sa.Column("warnings", JsonDocument, server_default=sa.text("'[]'"), nullable=False),
        sa.Column("started_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.Column("finished_at", UtcDateTime, nullable=True),
        sa.Column("external_refs", JsonDocument, server_default=sa.text("'{}'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id", "dataset_ver"],
            ["datasets.id", "datasets.version"],
            name="runs_dataset_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "runs_lookup",
        "runs",
        ["agent_id", "run_class", sa.text("started_at DESC")],
    )

    op.create_table(
        "run_steps",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        # NOT NULL while StepRecord.seq is optional: upsert_step allocates it.
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("served", JsonDocument, nullable=False),
        sa.Column("actual", JsonDocument, nullable=True),
        sa.Column("fetched_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.Column("recorded_at", UtcDateTime, nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"]),
        # The idempotency key. What makes fetch_step idempotent at the storage
        # layer rather than in application code.
        sa.PrimaryKeyConstraint("run_id", "node_id", "iteration", name="run_steps_pkey"),
        # Ruling R-37, an addition to contracts section 7. Wrapping the max(seq)
        # read and the insert in one transaction is not a lock over the value
        # read - the review reproduced two connections both committing seq = 1 -
        # so this constraint is what makes upsert_step's retry sound.
        sa.UniqueConstraint("run_id", "seq", name="run_steps_seq_key"),
    )

    if op.get_bind().dialect.name == "postgresql":
        op.create_index("datasets_labels_gin", "datasets", ["labels"], postgresql_using="gin")
        # datasets_search is contracts section 7's index, and ruling R-36 has
        # since superseded it: `q` is substring matching, by contract, so
        # Postgres uses ILIKE rather than full-text search and a to_tsvector
        # index cannot serve the query. It is dead rather than wrong - nothing
        # reads it, because find_datasets never emits to_tsvector - and it is
        # left here so the DDL and this revision still correspond.
        #
        # M7 replaces it with a pg_trgm GIN index, which does accelerate
        # substring matching, or drops it where the extension is unavailable.
        # Dropping it costs speed and nothing else: the conformance suite
        # asserts identical results, never identical plans.
        op.execute(
            "CREATE INDEX datasets_search ON datasets "
            "USING gin (to_tsvector('english', title || ' ' || intent))"
        )


def downgrade() -> None:
    """Downgrade schema.

    Dropping a table drops its indexes, so the two Postgres-only ones need no
    dialect branch here. Reverse dependency order, since the foreign keys are
    real on both dialects.
    """
    op.drop_table("run_steps")
    op.drop_table("runs")
    op.drop_table("skeletons")
    op.drop_table("datasets")
    op.drop_table("blueprints")
