"""initial schema: blueprints, datasets, skeletons, runs, run_steps

`docs/contracts.md` section 7's DDL, all five tables, for both SQL dialects.

Autogenerated from :data:`agentprops.storage.sql.METADATA` and then edited in
five places, each of which is a place autogenerate cannot know the intent:

1. **Column types are imported from `storage/sql.py`** rather than re-spelled.
   ``JsonDocument`` and ``UtcDateTime`` carry the two dialect differences
   contracts section 7 names - ``JSONB`` on Postgres, ``TIMESTAMPTZ`` on
   Postgres - so importing them is what keeps this migration and the adapter
   from disagreeing about a column's shape.
2. **``server_default`` uses ``sa.func.now()`` and ``sa.false()``**, not the
   SQLite literals autogenerate rendered (``(CURRENT_TIMESTAMP)`` and ``0``).
   ``DEFAULT 0`` on a boolean is an error on Postgres; these two render
   correctly on both.
3. **``runs_lookup`` is created outside batch mode** with a ``DESC`` third
   column. Batch mode exists to rebuild a table SQLite cannot ``ALTER``; on a
   table created three statements earlier it buys nothing and obscures the
   ``started_at DESC`` the index is for.
4. **The Postgres-only index is created in a dialect branch.**
   ``datasets_labels_gin`` has no SQLite equivalent - contracts section 7 says
   so, and says SQLite falls back to JSON extraction for labels, which is what
   ``find_datasets`` does. It is absent from ``METADATA`` (``create_all`` would
   try to build a GIN index on SQLite) and filtered out of autogenerate
   comparison by env.py, so neither dialect reports drift over it.

   Contracts section 7 declared a second one, ``datasets_search``, as a
   ``to_tsvector`` GIN index. **M7 dropped it, and ruling R-57 ratified
   that.** Ruling R-36 made ``q``
   substring matching by contract, R-39(a) then moved the fold and the match
   into Python because no SQL expression folds case identically across the
   three backends, and ``find_datasets`` therefore emits no SQL text match at
   all - so the index served no query and cost every write. R-36 offers
   ``pg_trgm`` instead and it would be dead for the same reason. See
   ``POSTGRES_ONLY_INDEXES`` in `storage/sql.py` for the measurement that
   closes the remaining option: an ``ILIKE`` prefilter is **not** a superset of
   ``str.casefold``, so it cannot be added without changing which rows ``q``
   returns.
5. **``UNIQUE (run_id, seq)`` on ``run_steps``** - an addition to contracts
   section 7 authorised by ruling R-37, and the constraint that makes
   ``upsert_step``'s ``seq`` allocation sound. See the note at the column.

6. **``skeletons.labels`` and ``skeletons.seed``** - an addition to contracts
   section 7 made at M5, for the reason ``Skeleton.labels`` records:
   ``dataset_skeleton`` takes both as inputs, ruling R-06 settles that neither
   is a fillable section, and ``dataset_submit(skeleton_id)`` takes nothing
   else, so they have to survive on the skeleton row.

Amended in M3's first fix round, again at M5, and again at M7, rather than
superseded by a second revision.
This is the *initial* schema of an unreleased milestone on an unmerged branch:
no database outside a temporary test file has ever been migrated by it, so
there is nothing for an additive revision to migrate *from*. A follow-up
revision would instead make every future deployment replay a SQLite table
rebuild (batch mode) to add a constraint that this statement can simply
declare. Recorded in `DECISIONS.md`; the rule it does not break is the real
one - never edit a revision that has been applied somewhere.

Revision ID: 0001
Revises:
Create Date: 2026-09-09

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from agentprops.storage.sql import JsonDocument, UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "blueprints",
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("document", JsonDocument, nullable=False),
        sa.Column("created_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("status IN ('draft', 'published')", name="blueprints_status_check"),
        sa.PrimaryKeyConstraint("agent_id", "version", name="blueprints_pkey"),
    )

    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("bp_version", sa.Text(), nullable=False),
        sa.Column("archived", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("labels", JsonDocument, nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=False),
        sa.Column("author_handle", sa.Text(), nullable=False),
        sa.Column("author_agent", sa.Text(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column("document", JsonDocument, nullable=False),
        # No DEFAULT now(): ruling R-09 populates this from
        # provenance.created_at so dataset_find's ordering survives an
        # export/import cycle.
        sa.Column("created_at", UtcDateTime, nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id", "bp_version"],
            ["blueprints.agent_id", "blueprints.version"],
            name="datasets_blueprint_fkey",
        ),
        sa.PrimaryKeyConstraint("id", "version", name="datasets_pkey"),
    )
    op.create_index("datasets_lookup", "datasets", ["agent_id", "bp_version", "archived"])
    op.create_index("datasets_author", "datasets", ["author_handle"])

    op.create_table(
        "skeletons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("bp_version", sa.Text(), nullable=False),
        sa.Column("labels", JsonDocument, nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("manifest", JsonDocument, nullable=False),
        sa.Column("parts", JsonDocument, server_default=sa.text("'{}'"), nullable=False),
        sa.Column("submitted_as", sa.Uuid(), nullable=True),
        sa.Column("created_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "runs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_ver", sa.Integer(), nullable=False),
        sa.Column("bp_version", sa.Text(), nullable=False),
        # Not in contracts section 7. Contracts section 2.3 gives Run a
        # `declared_blueprint_version` and the DDL has no column for it; see
        # storage/sql.py's note on the `runs` table and the M3 report.
        sa.Column("declared_bp_version", sa.Text(), nullable=True),
        sa.Column("run_class", sa.Text(), server_default=sa.text("'dev'"), nullable=False),
        sa.Column("model", JsonDocument, nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("outcome", JsonDocument, nullable=True),
        sa.Column("warnings", JsonDocument, server_default=sa.text("'[]'"), nullable=False),
        sa.Column("started_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.Column("finished_at", UtcDateTime, nullable=True),
        sa.Column("external_refs", JsonDocument, server_default=sa.text("'{}'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id", "dataset_ver"],
            ["datasets.id", "datasets.version"],
            name="runs_dataset_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "runs_lookup",
        "runs",
        ["agent_id", "run_class", sa.text("started_at DESC")],
    )

    op.create_table(
        "run_steps",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        # NOT NULL while StepRecord.seq is optional: upsert_step allocates it.
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("served", JsonDocument, nullable=False),
        sa.Column("actual", JsonDocument, nullable=True),
        sa.Column("fetched_at", UtcDateTime, server_default=sa.func.now(), nullable=False),
        sa.Column("recorded_at", UtcDateTime, nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"]),
        # The idempotency key. What makes fetch_step idempotent at the storage
        # layer rather than in application code.
        sa.PrimaryKeyConstraint("run_id", "node_id", "iteration", name="run_steps_pkey"),
        # Ruling R-37, an addition to contracts section 7. Wrapping the max(seq)
        # read and the insert in one transaction is not a lock over the value
        # read - the review reproduced two connections both committing seq = 1 -
        # so this constraint is what makes upsert_step's retry sound.
        sa.UniqueConstraint("run_id", "seq", name="run_steps_seq_key"),
    )

    if op.get_bind().dialect.name == "postgresql":
        op.create_index("datasets_labels_gin", "datasets", ["labels"], postgresql_using="gin")
        # There is deliberately no `datasets_search` here. See note 4 above: it
        # was contracts section 7's to_tsvector GIN index, ruling R-36
        # superseded it, and M7 dropped it rather than replacing it with the
        # pg_trgm index R-36 offers - because find_datasets issues no SQL text
        # match for either kind of index to serve.


def downgrade() -> None:
    """Downgrade schema.

    Dropping a table drops its indexes, so the Postgres-only one needs no
    dialect branch here. Reverse dependency order, since the foreign keys are
    real on both dialects.
    """
    op.drop_table("run_steps")
    op.drop_table("runs")
    op.drop_table("skeletons")
    op.drop_table("datasets")
    op.drop_table("blueprints")
