"""The four run tools. contracts section 4, Run table.

``run_start`` and ``fetch_step`` are the runtime, and phase 1 ships them **as
reads**: neither writes a dataset, and `service/runs.py` is where that is
enforced and `tests/unit/test_runtime_is_read_only.py` is where it is proved.
``run_get`` and ``run_find`` land here too, because ruling R-15 assigns them to
"M6 with the run storage they read".

``record_step`` and ``run_finish`` are M8's, ``run_evidence`` and ``run_export``
are M10's. All four are listed in `tests/unit/test_tool_surface.py`'s
``DEFERRED`` until then.

One deviation from the contract's parameter *order*, and none from its
parameter *set*: contracts section 4 lists ``run_start`` as ``run_id, agent_id,
declared_blueprint_version?, selector, model?, run_class?``, and Python cannot
put a required parameter after an optional one. ``selector`` therefore moves
ahead of ``declared_blueprint_version``. MCP arguments are passed by name, so
nothing a caller sends changes; making ``selector`` optional to preserve the
written order would have advertised it as omissible, which it is not.
"""

from __future__ import annotations

from typing import Any

from agentprops.models import RunQuery
from agentprops.server.app import bound, mcp
from agentprops.server.args import (
    ArgReader,
    IntArg,
    ObjectArg,
    OptionalObjectArg,
    OptionalTextArg,
    TextArg,
    reply,
)
from agentprops.service import failure, runs

__all__ = ["fetch_step", "run_find", "run_get", "run_start"]


@mcp.tool()
def run_start(
    run_id: TextArg,
    agent_id: TextArg,
    selector: ObjectArg,
    declared_blueprint_version: OptionalTextArg = None,
    model: OptionalObjectArg = None,
    run_class: OptionalTextArg = None,
) -> dict[str, Any]:
    """Start a run: pin one dataset version and one blueprint version to it.

    `run_id` is generated by *you*, before the first call, and is the
    idempotency key for the whole execution: 8 to 128 characters matching
    `^[A-Za-z0-9_.:-]+$`. Starting a run id that already exists returns that
    run unchanged - the pin never moves once set - and warns with
    `run_start_mismatch` if the arguments do not match the run that exists.

    `selector` is `{"dataset_id": "..."}` or `{"labels": {...}}`, exactly one.
    A label query that matches several datasets is assigned the oldest match
    and warns. `run_class` is `dev`, `eval` or `load`, defaulting to `dev`.

    Declaring a `declared_blueprint_version` other than the pinned one warns
    and serves anyway. Nothing here refuses to serve.
    """
    args = ArgReader()
    identifier = args.text("run_id", run_id)
    agent = args.text("agent_id", agent_id)
    chosen = args.mapping("selector", selector)
    declared = args.optional_text("declared_blueprint_version", declared_blueprint_version)
    info = args.optional_mapping("model", model)
    grade = args.optional_text("run_class", run_class)
    if args.errors:
        return reply(failure(args.errors))
    return reply(
        runs.start(bound(), identifier, agent, chosen, declared, model=info, run_class=grade)
    )


@mcp.tool()
def fetch_step(
    run_id: TextArg,
    node_id: OptionalTextArg = None,
    tool_name: OptionalTextArg = None,
    iteration: IntArg = None,
) -> dict[str, Any]:
    """Fetch the fixture for one step of a run. Idempotent, and never advances twice.

    Address the step with `node_id` (unambiguous, and what generated code
    should send) or with `tool_name`. A `tool_name` declared by several nodes is
    resolved against where the run currently is; if that still leaves a choice,
    the response is `RT-E01` naming every candidate node id, and you should
    retry with an explicit `node_id`. Nothing is ever guessed.

    `iteration` defaults to 0 and selects a pool entry for a `pool: true` node.
    Drawing past the end of the pool repeats the last entry and warns with
    `pool_exhausted` - it is never an error. A non-zero `iteration` on a node
    without a pool is `RT-E02`.

    Calling this twice with the same `(run_id, node_id, iteration)` returns the
    byte-identical fixture and records nothing new.
    """
    args = ArgReader()
    identifier = args.text("run_id", run_id)
    node = args.optional_text("node_id", node_id)
    tool = args.optional_text("tool_name", tool_name)
    index = args.number("iteration", iteration)
    if args.errors:
        return reply(failure(args.errors))
    return reply(
        runs.fetch_step(bound(), identifier, node_id=node, tool_name=tool, iteration=index)
    )


@mcp.tool()
def run_get(run_id: TextArg) -> dict[str, Any]:
    """Fetch one run in full: its pin, its steps, and its reconstructed path.

    `path` is not declared by anyone - it is rebuilt from the order the steps
    were served, so it is what the run actually did. `steps` and `path` are
    ordered by `(seq, node_id, iteration)`.
    """
    args = ArgReader()
    identifier = args.text("run_id", run_id)
    if args.errors:
        return reply(failure(args.errors))
    return reply(runs.get(bound(), identifier))


@mcp.tool()
def run_find(
    agent_id: OptionalTextArg = None,
    dataset_id: OptionalTextArg = None,
    run_class: OptionalTextArg = None,
    model: OptionalTextArg = None,
    limit: IntArg = None,
    offset: IntArg = None,
) -> dict[str, Any]:
    """Find runs, newest first. Summaries without the recorded outcome.

    Ordering is `(started_at DESC, id)`, which is total, so identical inputs
    return byte-identical output. `model` matches the model *name*. `limit`
    defaults to 50.
    """
    args = ArgReader()
    query = RunQuery(
        agent_id=args.optional_text("agent_id", agent_id),
        dataset_id=args.optional_text("dataset_id", dataset_id),
        run_class=args.optional_text("run_class", run_class),
        model=args.optional_text("model", model),
        limit=args.number("limit", limit),
        offset=args.number("offset", offset),
    )
    if args.errors:
        return reply(failure(args.errors))
    return reply(runs.find(bound(), query))
