"""M10's clause 2: the bundle is enough to grade a run, with **no store and no session**.

> `run_evidence` output is sufficient for the client's comparison helpers to
> grade the run with no further server calls.

The only way to prove that means anything is to do it: take a bundle the service
really emitted, hand it to `compare`, and grade. So this file loads the committed
bundle from `tests/fixtures/evidence/` - regenerated by
`scripts/make_evidence_fixture.py` and held to the live service's output by
`test_service_evidence.py` - and grades it in all three modes.

"No store and no session" is measured, twice
--------------------------------------------

A test that *happens* not to touch a store proves nothing, because this pytest
process has a store, a session and the whole service imported by the time it
runs. Two guards make the claim mechanical instead:

- :func:`test_this_module_imports_no_service_and_no_session` reads **this file's
  own AST** and asserts its imports are exactly the four it declares. Cheap, and
  it fails on the line that made the mistake possible;
- :func:`test_the_bundle_grades_in_an_interpreter_with_no_agentprops` runs the
  whole grading in a **fresh subprocess where importing anything named
  ``agentprops`` raises**. Not "did not happen to import" - *cannot*. If any
  part of grading needed the service, the subprocess dies.

The second guard has its own control, because a blocker that blocks nothing
would let the probe pass while proving nothing - the vacuity failure this build
has paid for four times (ruling R-77(e)):
:func:`test_the_import_blocker_actually_blocks` asserts that ``import
agentprops`` inside that interpreter fails, and that ``import
agentprops_client.compare`` still succeeds. Both halves: a blocker that blocked
*everything* would be equally useless.

What is graded, and the perturbations
-------------------------------------

The golden run's recorded outcome is `priya-missing-docs`'s own
``expected.final``, so the honest expectation is that all three modes pass -
which on its own is a test that could not tell a sufficient bundle from a
vacuous one. So each mode is graded twice: once as the service emitted it, and
once against a **locally perturbed** copy, asserting the helper reports the
difference and names it with a pointer. The perturbations are local to this
file - no server involved - which is the point: a caller holding this bundle can
answer both questions.

``subset``'s vacuity hazard gets the same treatment. ``subset({}, anything)`` is
``ok``, so a bundle whose ``expected.final`` was empty would pass every run;
:func:`test_the_expectation_is_not_vacuous` asserts the bundle's expectation is a
non-empty object before any mode is graded, which is DS-021's guarantee checked
where it is being relied on.
"""

from __future__ import annotations

import ast
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Final

import pytest

from agentprops_client.compare import (
    COMPARISON_MODES,
    MODE_EXACT,
    MODE_SCHEMA,
    MODE_SUBSET,
    exact,
    grade,
    schema,
    subset,
)

#: The bundle, and the path is spelled out rather than imported from
#: `conftest.py` because importing that module would import the service - which
#: is the one thing this file may not do.
BUNDLE_PATH: Final[Path] = (
    Path(__file__).parents[1] / "fixtures" / "evidence" / "priya-missing-docs-run.json"
)

#: Everything this module may import. Asserted against its own AST below.
#:
#: ``agentprops_client.compare`` is the only product module on the list, and
#: that is the whole claim: a grader has the client's three pure functions and
#: nothing else. ``agentprops`` (the service), ``agentprops_client.session`` (the
#: transport) and `conftest` (which imports the service) are all absent, and
#: each would be a different way of failing the same clause.
ALLOWED_IMPORTS: Final[frozenset[str]] = frozenset(
    {"__future__", "ast", "json", "subprocess", "sys", "pathlib", "typing", "pytest"}
)

#: The one product module this file may name.
ALLOWED_PRODUCT_IMPORT: Final = "agentprops_client.compare"


def bundle() -> dict[str, Any]:
    """The committed bundle, parsed. ``json`` and a path - no service, no client."""
    document: dict[str, Any] = json.loads(BUNDLE_PATH.read_text(encoding="utf-8"))
    return document


BUNDLE: Final[dict[str, Any]] = bundle()


# ------------------------------------------------------- the bundle is complete


def test_the_bundle_carries_every_argument_the_three_helpers_take() -> None:
    """Ruling R-82's general form, as an assertion rather than a reading.

    "The bundle must carry everything the three helpers take as input."
    ``exact`` and ``subset`` take an expected and an actual; ``schema`` takes an
    instance and a **schema**; ``grade`` takes the mode. Four values, and this
    is the list of them - so a bundle that dropped one fails here rather than in
    whichever mode happened to need it.
    """
    assert BUNDLE["comparison"] in COMPARISON_MODES, BUNDLE["comparison"]
    assert isinstance(BUNDLE["expected"]["final"], dict)
    assert isinstance(BUNDLE["actual"], dict)
    assert isinstance(BUNDLE["outcome_schema"], dict)


def test_the_outcome_schema_is_the_schema_and_not_a_reference() -> None:
    """R-82's specific ruling: the schema **itself**, because a reference is a call.

    A ``{"$ref": "..."}``, a version string or an agent id here would each mean
    the caller has to ask the service for the real thing, which is the further
    server call the clause forbids. So the assertion is that it is a usable
    Draft 2020-12 schema: it has keywords, and ``schema()`` actually validates
    against it.
    """
    outcome_schema = BUNDLE["outcome_schema"]
    assert "$ref" not in outcome_schema, "a reference is another server call (R-82)"
    assert outcome_schema.get("type") == "object"
    assert set(outcome_schema.get("required", [])) == {"onboarding_status", "outstanding_tasks"}


def test_the_expectation_is_not_vacuous() -> None:
    """``subset({}, anything)`` is ``ok``, so an empty expectation passes every run.

    DS-021 requires ``expected.final`` to be a non-empty object and the
    authoring flow is what enforces it - but this file *relies* on that, so it
    checks it here rather than trusting a rule enforced two milestones away.
    """
    assert BUNDLE["expected"]["final"], "an empty expected.final grades every run as passing"


# ------------------------------------------------------------- grading the run


def test_grade_dispatches_on_the_declared_mode_and_passes() -> None:
    """The whole clause in one call. Nothing here knows a server exists.

    ``grade`` is handed the mode the *dataset* declared, so this test does not
    choose a comparison either - which is what "carrying the mode on the
    dataset means every consumer grades it the same way" buys.
    """
    answer = grade(
        BUNDLE["comparison"],
        BUNDLE["expected"]["final"],
        BUNDLE["actual"],
        outcome_schema=BUNDLE["outcome_schema"],
    )
    assert answer, str(answer)
    assert answer.mode == MODE_SUBSET


@pytest.mark.parametrize("mode", sorted(COMPARISON_MODES))
def test_every_mode_grades_this_bundle(mode: str) -> None:
    """All three, not just the declared one.

    The bundle has to serve whichever mode a *caller* applies - a team may grade
    the same run more strictly than the author declared - so each of the three
    is exercised against the same document.
    """
    answer = grade(
        mode, BUNDLE["expected"]["final"], BUNDLE["actual"], outcome_schema=BUNDLE["outcome_schema"]
    )
    assert answer, str(answer)
    assert answer.mode == mode


def test_exact_and_subset_report_a_perturbed_outcome() -> None:
    """The losing side. A test that only ever passes cannot tell a bundle from a stub.

    The perturbation is local to this file, which is the point: a caller holding
    the bundle can answer "did it match" *and* "where did it differ", with an
    RFC 6901 pointer, without asking the service anything.
    """
    wrong = {**BUNDLE["actual"], "outstanding_tasks": 3}
    for answer in (
        exact(BUNDLE["expected"]["final"], wrong),
        subset(BUNDLE["expected"]["final"], wrong),
    ):
        assert not answer, str(answer)
        assert [item.pointer for item in answer.differences] == ["/outstanding_tasks"]
        assert answer.differences[0].expected == 0
        assert answer.differences[0].actual == 3


def test_schema_reports_an_outcome_the_pinned_schema_rejects() -> None:
    """``schema`` mode's losing side, and it needs the schema to have one.

    ``onboarding_status`` is an enum of ``complete`` and ``escalated``, so a
    third value is a finding whose ``reason`` is the failing keyword - which is
    only available because the bundle carries the schema and not a name for it.
    """
    answer = schema(
        {**BUNDLE["actual"], "onboarding_status": "half-done"}, BUNDLE["outcome_schema"]
    )
    assert not answer, str(answer)
    assert [item.reason for item in answer.differences] == ["enum"]
    assert [item.pointer for item in answer.differences] == ["/onboarding_status"]


def test_exact_is_stricter_than_subset_on_this_bundle() -> None:
    """The two modes are not the same function, measured on this document.

    An extra key in the actual is ignored by ``subset`` and reported by
    ``exact``. Without this, a bundle could satisfy every test above while the
    two modes were secretly one - and the dataset's declared ``subset`` would
    mean nothing.
    """
    extra = {**BUNDLE["actual"], "audit_note": "reviewed"}
    assert subset(BUNDLE["expected"]["final"], extra)
    assert not exact(BUNDLE["expected"]["final"], extra)


# ------------------------------------------------------ grading the steps and path


def test_every_recorded_step_grades_from_the_bundle_alone() -> None:
    """The per-node half of the bundle: ``expected`` beside ``actual``, per step.

    "Per-node expected versus actual" is one of the bundle's stated contents,
    and this is what it is *for*: ``exact`` on the pair. The golden run recorded
    the served output at every step, so all of them match - and the unrecorded
    step is excluded by ``recorded``, which is the field that makes the
    distinction available at all.
    """
    recorded = [node for node in BUNDLE["nodes"] if node["recorded"]]
    assert len(recorded) == len(BUNDLE["nodes"]) - 1, "expected exactly one unrecorded step"
    for node in recorded:
        answer = exact(node["expected"], node["actual"])
        assert answer, f"{node['node_id']} iteration {node['iteration']}: {answer}"


def test_the_unrecorded_step_is_distinguishable_from_a_null_actual() -> None:
    """``recorded: false`` says "never reported", which ``actual: null`` cannot.

    contracts 2.2's "``null`` is not absence" one level out. A grader that read
    ``actual`` alone would call an unreported step a step that returned
    ``null``, and would then grade it as a mismatch against the authored output.
    """
    unrecorded = [node for node in BUNDLE["nodes"] if not node["recorded"]]
    assert [node["node_id"] for node in unrecorded] == ["check_docs"]
    assert unrecorded[0]["actual"] is None
    assert unrecorded[0]["expected"] is not None, "the authored output is still evidence"


def test_a_node_expectation_about_an_uncalled_node_is_answerable() -> None:
    """``escalate: {"called": false}`` is checkable because ``nodes`` is per served step.

    The dataset expects ``escalate`` never to be called. The bundle lists one
    entry per step that was *served*, so the absence of ``escalate`` from
    ``nodes`` - and from ``path.actual`` - is the evidence, and no further call
    is needed to establish it.
    """
    expectations = BUNDLE["expected"]["node_expectations"]
    uncalled = [node_id for node_id, rule in expectations.items() if rule.get("called") is False]
    assert uncalled == ["escalate"]
    served = {node["node_id"] for node in BUNDLE["nodes"]}
    assert set(uncalled).isdisjoint(served)
    assert set(uncalled).isdisjoint(BUNDLE["path"]["actual"])


def test_the_two_paths_are_present_and_carry_no_verdict() -> None:
    """The bundle juxtaposes them; the *client* compares them.

    Ground rule 2 is "there is no comparison logic in the server", so ``path``
    has no ``matches``, no divergence index and no missing-node set - and
    ``exact`` on the two lists is the comparison, available here with no server.

    This run's paths deliberately differ, and the reason is a finding rather
    than a defect: ``expected_path`` visits ``check_docs`` twice while
    ``fetch_step`` is idempotent per ``(node_id, iteration)``, so the
    reconstructed path cannot repeat it. The assertion is therefore that the
    client can *see* the difference and name where it starts - which is exactly
    what a service-side verdict would have taken away.
    """
    paths = BUNDLE["path"]
    assert set(paths) == {"expected", "actual", "traversed"}
    answer = exact(paths["expected"], paths["actual"])
    assert not answer, "the golden run's two paths differ; see the docstring"
    assert answer.differences[0].pointer == "/4", answer.differences


# --------------------------------------------------------------- the two guards


def imports_of(source: str) -> set[str]:
    """Every module named by an ``import`` in ``source``. Both spellings."""
    found: set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Import):
            found.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            found.add(node.module)
    return found


def test_this_module_imports_no_service_and_no_session() -> None:
    """This file's own imports, from its own AST. The cheap half of the claim.

    An allowlist rather than a denylist, for `test_client_import_isolation.py`'s
    reason: a denylist holds only against the module names someone thought of.
    """
    imported = imports_of(Path(__file__).read_text(encoding="utf-8"))
    offences = imported - ALLOWED_IMPORTS - {ALLOWED_PRODUCT_IMPORT}
    assert not offences, (
        f"this file must grade with no store and no session, and imports {sorted(offences)}"
    )
    assert ALLOWED_PRODUCT_IMPORT in imported, "the guard is vacuous if nothing is graded"


def test_the_import_guard_would_catch_a_store_or_a_session() -> None:
    """The guard above, run against the three things it forbids. Ruling R-77(e).

    ``agentprops.service`` is a store, ``agentprops_client.session`` is a
    transport, and `conftest` is both by transitive import - the third being the
    one an author would reach for without thinking, because every other file in
    this directory does. All three must be reported, and the sanctioned import
    must not be.
    """
    offending = "\n".join(
        (
            "from agentprops.service import sqlite_context",
            "from agentprops_client.session import Session",
            "from conftest import FIXTURES_DIR",
            "from agentprops_client.compare import grade",
        )
    )
    reported = imports_of(offending) - ALLOWED_IMPORTS - {ALLOWED_PRODUCT_IMPORT}
    assert reported == {"agentprops.service", "agentprops_client.session", "conftest"}, reported


#: What the subprocess guard runs: block ``agentprops``, then grade.
_GRADING_PROBE: Final = """
import json, sys

class Blocker:
    def find_module(self, name, path=None):
        return None
    def find_spec(self, name, path=None, target=None):
        if name == 'agentprops' or name.startswith('agentprops.'):
            raise ImportError('the service is not importable in this interpreter: ' + name)
        return None

sys.meta_path.insert(0, Blocker())
from agentprops_client.compare import grade
bundle = json.load(open(sys.argv[1], encoding='utf-8'))
answer = grade(
    bundle['comparison'],
    bundle['expected']['final'],
    bundle['actual'],
    outcome_schema=bundle['outcome_schema'],
)
print('graded', answer.mode, answer.ok)
"""


def probe(source: str, *arguments: str) -> subprocess.CompletedProcess[str]:
    """Run ``source`` in a fresh interpreter. No ``check``: failures are the point."""
    return subprocess.run(
        [sys.executable, "-c", source, *arguments], capture_output=True, text=True, check=False
    )


def test_the_bundle_grades_in_an_interpreter_with_no_agentprops() -> None:
    """The strong half: grading cannot reach the service, not merely does not.

    A meta-path finder that raises for ``agentprops`` and anything under it,
    installed before the client is imported. If ``compare`` - or ``jsonschema``,
    or the bundle - needed one line of the service, this dies with the
    ``ImportError`` the blocker raises.
    """
    finished = probe(_GRADING_PROBE, str(BUNDLE_PATH))
    assert finished.returncode == 0, finished.stderr
    assert finished.stdout.strip() == "graded subset True", finished.stdout


def test_the_import_blocker_actually_blocks() -> None:
    """The guard's own guard, both ways. Ruling R-77(e): run it against what it forbids.

    A blocker that blocked nothing would make the test above pass while proving
    nothing at all, which is the vacuity this build has shipped three times. So
    the blocker is shown to **fail** on ``import agentprops`` and to **allow**
    ``import agentprops_client.compare`` - because one that blocked everything
    would be just as useless a control.
    """
    blocked = probe(
        _GRADING_PROBE.replace(
            "from agentprops_client.compare", "import agentprops\nfrom agentprops_client.compare"
        ),
        str(BUNDLE_PATH),
    )
    assert blocked.returncode != 0, "the blocker let the service through"
    assert "not importable in this interpreter: agentprops" in blocked.stderr, blocked.stderr

    allowed = probe(
        _GRADING_PROBE.replace(
            "print('graded'", "import agentprops_client.compare\nprint('graded'"
        ),
        str(BUNDLE_PATH),
    )
    assert allowed.returncode == 0, f"the blocker also blocked the client: {allowed.stderr}"


def test_the_modes_are_the_three_the_dataset_may_declare() -> None:
    """``exact``, ``schema``, ``subset`` - and ``semantic`` is not one of them.

    A judge is an LLM and ground rule 4 puts none in the service *or* the
    client. Asserted here because this file is where a caller's whole grading
    vocabulary is exercised.
    """
    assert {MODE_EXACT, MODE_SCHEMA, MODE_SUBSET} == COMPARISON_MODES
    assert "semantic" not in COMPARISON_MODES
    with pytest.raises(ValueError, match="unknown comparison mode"):
        grade("semantic", {}, {})
