"""The run client: the generated id, the requests it sends, and sync/async parity.

`test_worked_example_end_to_end.py` drives both clients through the whole M8
script against a live server, which is the acceptance clause. This file holds
the properties that are cheaper and clearer to assert without one:

**The id is generated at construction** (PRD 5.4), before the first call, and
is the same on every call in the run. :func:`test_the_run_id_is_generated_once`
and :func:`test_every_request_carries_the_run_id` are that sentence, and the
second is the one with teeth: a client that generated an id per *call* would
satisfy the first.

**Sync and async send the same requests.** They are two facades over one set of
request builders, so :func:`test_the_two_clients_send_identical_requests`
records the calls each one makes and compares them - which is the assertion the
split exists to make trivially true, and the one that would catch a parameter
added to one facade and forgotten in the other.

**Omitted arguments are omitted, not sent as null.** A ``fetch_step`` without an
``iteration`` must not send ``iteration: null``, because "absent" and "null" are
different things to the tool surface and relying on them being the same is
relying on something nothing asserts.

The transport here is a **recording double**, not a server. `run.py` takes a
callable, which is what makes that possible - and is the same property that
keeps the module free of a network import.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Final

import pytest

from agentprops.service import runs as service_runs
from agentprops_client.envelope import ToolError
from agentprops_client.run import (
    RUN_ID_MAX_LENGTH,
    RUN_ID_MIN_LENGTH,
    STATUS_ABANDONED,
    STATUS_FINISHED,
    AsyncRunClient,
    RunClient,
    new_run_id,
)

AGENT: Final = "location-onboarding"
RUN_ID: Final = "m8-client-unit-run"

#: What a successful ``fetch_step`` looks like on the wire, minimally.
STEP_ENVELOPE: Final[dict[str, Any]] = {
    "ok": True,
    "data": {"step": {"fixture": {"output": {"store_id": "ST-4471"}}, "resolved_node_id": "n"}},
    "warnings": [{"code": "pool_exhausted", "detail": {"node_id": "n", "iteration": 2}}],
}


class Recorder:
    """A transport that records every call and answers a canned envelope.

    Both facades take a callable, so one double serves both - the sync client
    calls it and the async client awaits :meth:`acall`, which delegates. That
    shared answer is what makes the parity comparison meaningful: the two
    clients are driven by the *same* double, so any difference in the recording
    is a difference in the clients.
    """

    def __init__(self, envelope: Mapping[str, Any] | None = None) -> None:
        self.calls: list[tuple[str, dict[str, Any]]] = []
        self.envelope = dict(envelope or STEP_ENVELOPE)

    def __call__(self, tool: str, arguments: dict[str, Any]) -> Mapping[str, Any]:
        self.calls.append((tool, dict(arguments)))
        return self.envelope

    async def acall(self, tool: str, arguments: dict[str, Any]) -> Mapping[str, Any]:
        return self(tool, arguments)

    @property
    def tools(self) -> list[str]:
        return [tool for tool, _ in self.calls]


def sync_client(recorder: Recorder, run_id: str | None = RUN_ID) -> RunClient:
    return RunClient(recorder, agent_id=AGENT, run_id=run_id)


def async_client(recorder: Recorder, run_id: str | None = RUN_ID) -> AsyncRunClient:
    return AsyncRunClient(recorder.acall, agent_id=AGENT, run_id=run_id)


# ------------------------------------------------------------------- the run id


def test_the_run_id_is_generated_once() -> None:
    """PRD 5.4: generated by the client library when it is initialised.

    Two clients get two ids - so it is generated rather than constant - and one
    client's id does not move, which is what makes it an idempotency key.
    """
    first = RunClient(Recorder(), agent_id=AGENT)
    second = RunClient(Recorder(), agent_id=AGENT)
    assert first.run_id != second.run_id, "the id is a constant, not a generated value"
    assert first.run_id == first.run_id
    assert AsyncRunClient(Recorder().acall, agent_id=AGENT).run_id != first.run_id


def test_a_generated_run_id_is_one_the_service_accepts() -> None:
    """contracts 2.3's shape, checked against the *service's* own constants.

    Imported from `service/runs.py` rather than restated, because the point is
    that the two agree: a client that minted an id the service refuses would
    fail at ``run_start`` with ``AP-001`` and the developer would have no idea
    why.
    """
    assert (RUN_ID_MIN_LENGTH, RUN_ID_MAX_LENGTH) == (
        service_runs.RUN_ID_MIN_LENGTH,
        service_runs.RUN_ID_MAX_LENGTH,
    )
    for _ in range(20):
        generated = new_run_id()
        assert service_runs.RUN_ID_PATTERN.fullmatch(generated), generated
        assert service_runs.RUN_ID_MIN_LENGTH <= len(generated) <= service_runs.RUN_ID_MAX_LENGTH


def test_a_supplied_run_id_is_checked_at_construction() -> None:
    """A bad id fails before the run exists, rather than one call later.

    The service is still the authority - it answers ``AP-001`` for the same
    three things - but a library argument is the one place raising is right, and
    failing at construction means the traceback names the line that chose the
    id.
    """
    assert sync_client(Recorder(), "valid.id-1:2").run_id == "valid.id-1:2"
    with pytest.raises(ValueError, match="characters"):
        sync_client(Recorder(), "short")
    with pytest.raises(ValueError, match="characters"):
        sync_client(Recorder(), "x" * (RUN_ID_MAX_LENGTH + 1))
    with pytest.raises(ValueError, match="must match"):
        sync_client(Recorder(), "spaces are not allowed")
    with pytest.raises(ValueError, match="must match"):
        sync_client(Recorder(), "slash/es")


def test_every_request_carries_the_run_id() -> None:
    """The property PRD 5.4 actually asks for, and the one a per-call id would break.

    Four different calls, one id. A client that generated an id per call would
    pass :func:`test_the_run_id_is_generated_once` and fail here, which is why
    both exist.
    """
    recorder = Recorder({"ok": True, "data": {"run": {}}, "warnings": []})
    client = sync_client(recorder)
    client.run_finish({"onboarding_status": "complete"})
    recorder.envelope = dict(STEP_ENVELOPE)
    client.fetch_step(node_id="receive_request")
    recorder.envelope = {
        "ok": True,
        "data": {"record": {"step": {"actual": {}}, "resolved_node_id": "n"}},
        "warnings": [],
    }
    client.record_step({}, node_id="receive_request")

    assert {arguments["run_id"] for _, arguments in recorder.calls} == {client.run_id}
    assert len(recorder.calls) == 3


# ------------------------------------------------------------- request shaping


def test_an_omitted_argument_is_omitted_rather_than_null() -> None:
    """ "Absent" and "null" are different things to the tool surface.

    ``fetch_step`` with no ``iteration`` must send no ``iteration`` key at all.
    The surface happens to treat a null the same way today, and a client that
    depended on that would be depending on something nothing asserts - which is
    how a coincidence becomes a contract.
    """
    recorder = Recorder()
    sync_client(recorder).fetch_step(node_id="receive_request")
    tool, arguments = recorder.calls[0]
    assert tool == "fetch_step"
    assert arguments == {"run_id": RUN_ID, "node_id": "receive_request"}
    assert "iteration" not in arguments and "tool_name" not in arguments


def test_a_zero_iteration_is_still_sent() -> None:
    """The bug the "drop the Nones" rule invites: ``0`` is falsy and must survive.

    A request builder written with ``if value:`` instead of
    ``if value is not None:`` drops ``iteration: 0`` - which the surface then
    defaults to 0 anyway, so nothing breaks and nothing says so. Until the same
    rule drops an ``outstanding_tasks: 0`` from an outcome.
    """
    recorder = Recorder()
    sync_client(recorder).fetch_step(node_id="request_docs", iteration=0)
    assert recorder.calls[0][1]["iteration"] == 0


def test_run_start_sends_every_optional_it_was_given() -> None:
    recorder = Recorder({"ok": True, "data": {"start": {"run": {}, "pin": {}}}, "warnings": []})
    sync_client(recorder).run_start(
        {"labels": {"scenario": "missing-documents"}},
        declared_blueprint_version="1.1.0",
        model={"provider": "anthropic", "name": "claude-opus-5", "version": "20260401"},
        run_class="eval",
    )
    assert recorder.calls[0][1] == {
        "run_id": RUN_ID,
        "agent_id": AGENT,
        "selector": {"labels": {"scenario": "missing-documents"}},
        "declared_blueprint_version": "1.1.0",
        "model": {"provider": "anthropic", "name": "claude-opus-5", "version": "20260401"},
        "run_class": "eval",
    }


def test_run_finish_defaults_to_finished_and_sends_the_status_it_is_given() -> None:
    """``status`` is required by the tool, so the client must always send one."""
    recorder = Recorder({"ok": True, "data": {"run": {}}, "warnings": []})
    client = sync_client(recorder)
    client.run_finish({})
    client.run_finish({}, status=STATUS_ABANDONED)
    assert [arguments["status"] for _, arguments in recorder.calls] == [
        STATUS_FINISHED,
        STATUS_ABANDONED,
    ]


def test_the_client_copies_the_documents_it_is_handed() -> None:
    """A caller's dict must not become a live reference inside a request.

    An agent that reuses one ``actual`` dict across steps, mutating it in place,
    would otherwise have every recorded step carry the last version.
    """
    recorder = Recorder(
        {"ok": True, "data": {"record": {"step": {}, "resolved_node_id": "n"}}, "warnings": []}
    )
    actual: dict[str, Any] = {"received": []}
    sync_client(recorder).record_step(actual, node_id="request_docs", iteration=0)
    actual["received"] = ["fssai"]
    assert recorder.calls[0][1]["actual"] == {"received": []}


# ------------------------------------------------------------ sync/async parity


async def test_the_two_clients_send_identical_requests() -> None:
    """The whole point of the split: one set of request builders, two facades.

    Every method, on both clients, driven by the same double with the same
    canned answers - so the recorded calls must be identical. A parameter added
    to one facade and forgotten in the other fails here.
    """
    envelopes: dict[str, dict[str, Any]] = {
        "run_start": {"ok": True, "data": {"start": {"run": {}, "pin": {}}}, "warnings": []},
        "fetch_step": dict(STEP_ENVELOPE),
        "record_step": {
            "ok": True,
            "data": {"record": {"step": {"actual": {"a": 1}}, "resolved_node_id": "n"}},
            "warnings": [],
        },
        "run_finish": {"ok": True, "data": {"run": {"status": "finished"}}, "warnings": []},
    }

    class Routing(Recorder):
        def __call__(self, tool: str, arguments: dict[str, Any]) -> Mapping[str, Any]:
            self.calls.append((tool, dict(arguments)))
            return envelopes[tool]

    sync_recorder, async_recorder = Routing(), Routing()
    sync = sync_client(sync_recorder)
    asynchronous = async_client(async_recorder)

    sync.run_start({"dataset_id": "d"}, run_class="eval")
    sync.fetch_step(tool_name="acme.stores.get")
    sync.fetch_step(node_id="request_docs", iteration=1)
    sync.record_step({"a": 1}, node_id="request_docs", iteration=1)
    sync.run_finish({"onboarding_status": "complete"}, status=STATUS_ABANDONED)

    await asynchronous.run_start({"dataset_id": "d"}, run_class="eval")
    await asynchronous.fetch_step(tool_name="acme.stores.get")
    await asynchronous.fetch_step(node_id="request_docs", iteration=1)
    await asynchronous.record_step({"a": 1}, node_id="request_docs", iteration=1)
    await asynchronous.run_finish({"onboarding_status": "complete"}, status=STATUS_ABANDONED)

    assert sync_recorder.tools == [
        "run_start",
        "fetch_step",
        "fetch_step",
        "record_step",
        "run_finish",
    ]
    assert async_recorder.tools == sync_recorder.tools
    without_id = [
        (tool, {name: value for name, value in arguments.items() if name != "run_id"})
        for tool, arguments in sync_recorder.calls
    ]
    assert without_id == [
        (tool, {name: value for name, value in arguments.items() if name != "run_id"})
        for tool, arguments in async_recorder.calls
    ]


async def test_the_two_clients_read_identical_results() -> None:
    """Parity on the way back as well, including the typed accessors."""
    recorder = Recorder()
    sync = sync_client(recorder).fetch_step(node_id="n")
    asynchronous = await async_client(recorder).fetch_step(node_id="n")
    assert sync == asynchronous
    assert sync.output == {"store_id": "ST-4471"}
    assert [item.code for item in sync.warnings] == ["pool_exhausted"]


async def test_both_clients_have_the_same_public_surface() -> None:
    """A method added to one and not the other is a drift this catches.

    Compared as name sets rather than by calling them, so it covers a method
    nobody thought to test - which is the kind the two facades would drift on.
    """

    def surface(client: object) -> set[str]:
        return {
            name
            for name in dir(client)
            if not name.startswith("_") and callable(getattr(client, name))
        }

    assert surface(sync_client(Recorder())) == surface(async_client(Recorder()))


# ------------------------------------------------------------------- failures


def test_a_failure_envelope_raises_with_the_findings() -> None:
    """The typed methods raise; the exception carries every finding.

    Not a bare ``AssertionError`` and not a swallowed ``None``: a caller
    handling ``RT-E03`` reads ``rule`` off the findings, which is the same thing
    a caller of any other client in this product does.
    """
    recorder = Recorder(
        {
            "ok": False,
            "errors": [
                {
                    "rule": "RT-E03",
                    "severity": "error",
                    "pointer": "/run_id",
                    "message": "no run",
                    "section": None,
                    "context": {"run_id": RUN_ID},
                }
            ],
        }
    )
    with pytest.raises(ToolError) as raised:
        sync_client(recorder).fetch_step(node_id="n")
    assert raised.value.rules() == ("RT-E03",)
    assert raised.value.findings[0].pointer == "/run_id"
    assert raised.value.findings[0].context["run_id"] == RUN_ID
    assert "fetch_step" in str(raised.value), "the exception names the request"


def test_call_returns_a_failure_envelope_without_raising() -> None:
    """The escape hatch. Ground rule 3's answers are data, and stay data.

    ``call`` is how the authoring tools are reached and how a caller inspects a
    rejection - a ``dataset_submit`` that reports ``DS-017`` is *information*,
    and a client that raised would make the repair loop PRD 6 flow B describes
    into exception handling.
    """
    recorder = Recorder(
        {
            "ok": False,
            "errors": [
                {
                    "rule": "SK-002",
                    "severity": "error",
                    "pointer": "/section",
                    "message": "out of order",
                    "section": "entities",
                    "context": {},
                }
            ],
        }
    )
    envelope = sync_client(recorder).call("dataset_fill_part", section="entities", content={})
    assert envelope.ok is False
    assert envelope.rules() == ("SK-002",)
    assert envelope.errors[0].section == "entities"
    assert not envelope, "an envelope is falsy when it failed"


def test_a_warning_never_raises() -> None:
    """Ground rule 3 in the client: a mismatch is a warning, not an exception.

    The canned envelope carries ``pool_exhausted`` on a successful response, and
    the call must return normally with the warning attached. A client that
    raised on a warning would re-introduce the gate the service refuses to be.
    """
    step = sync_client(Recorder()).fetch_step(node_id="request_docs", iteration=2)
    assert [item.code for item in step.warnings] == ["pool_exhausted"]
    assert step.warnings[0].detail["iteration"] == 2


def test_a_protocol_level_error_is_not_mistaken_for_a_failure_envelope() -> None:
    """A transport that answers nothing is a different fault from a tool saying no.

    ``read_envelope`` refuses to invent an answer: ``None`` and a payload that
    is not one of the two section 1 shapes both raise ``ValueError`` rather than
    becoming an empty :class:`ToolError`, because "the server said no" and
    "nobody answered" need different handling.
    """
    with pytest.raises(ValueError, match="no structured content"):
        RunClient(lambda tool, arguments: None, agent_id=AGENT, run_id=RUN_ID).fetch_step(
            node_id="n"
        )
    with pytest.raises(ValueError, match="not an agent-props envelope"):
        RunClient(
            lambda tool, arguments: {"result": "fine"}, agent_id=AGENT, run_id=RUN_ID
        ).fetch_step(node_id="n")


def test_a_success_envelope_missing_the_payload_key_is_not_a_tool_failure() -> None:
    """A client asking for the wrong key must not report the tool as having failed."""
    recorder = Recorder({"ok": True, "data": {"something_else": {}}, "warnings": []})
    with pytest.raises(ValueError, match="no 'step' payload"):
        sync_client(recorder).fetch_step(node_id="n")
